string=[5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6,5,6]
prods_com="0x0302bafdc1322e8c7c13a308ae1b1805e4f9cdb4fb007cca2e3b729797e17f31"
mem_proofs_prod=[0,2,3,4,1,2,3,4,1,2,3,4,1,2,3]
[[prods]]
parent.label=1
parent.idx=0
childL.label=2
childL.idx=1
childR.label=2
childR.idx=6
[[prods]]
parent.label=2
parent.idx=1
childL.label=3
childL.idx=2
childR.label=4
childR.idx=4
[[prods]]
parent.label=3
parent.idx=2
childL.label=5
childL.idx=3
childR.label=0
childR.idx=0
[[prods]]
parent.label=4
parent.idx=4
childL.label=6
childL.idx=5
childR.label=0
childR.idx=0
[[prods]]
parent.label=2
parent.idx=6
childL.label=2
childL.idx=7
childR.label=2
childR.idx=12
[[prods]]
parent.label=2
parent.idx=7
childL.label=3
childL.idx=8
childR.label=4
childR.idx=10
[[prods]]
parent.label=3
parent.idx=8
childL.label=5
childL.idx=9
childR.label=0
childR.idx=0
[[prods]]
parent.label=4
parent.idx=10
childL.label=6
childL.idx=11
childR.label=0
childR.idx=0
[[prods]]
parent.label=2
parent.idx=12
childL.label=2
childL.idx=13
childR.label=2
childR.idx=18
[[prods]]
parent.label=2
parent.idx=13
childL.label=3
childL.idx=14
childR.label=4
childR.idx=16
[[prods]]
parent.label=3
parent.idx=14
childL.label=5
childL.idx=15
childR.label=0
childR.idx=0
[[prods]]
parent.label=4
parent.idx=16
childL.label=6
childL.idx=17
childR.label=0
childR.idx=0
[[prods]]
parent.label=2
parent.idx=18
childL.label=2
childL.idx=19
childR.label=2
childR.idx=24
[[prods]]
parent.label=2
parent.idx=19
childL.label=3
childL.idx=20
childR.label=4
childR.idx=22
[[prods]]
parent.label=3
parent.idx=20
childL.label=5
childL.idx=21
childR.label=0
childR.idx=0

